#include "PluginStateModel.h"
#include <iostream>
namespace { bool ok=true; void check(bool v,const char* n){std::cout<<(v?"PASS ":"FAIL ")<<n<<'\n';ok&=v;} juce::MemoryBlock bytes(const PluginStateModel& s){juce::MemoryBlock b;if(auto x=s.toValueTree().createXml())copyXmlToBinary(*x,b);return b;} double now(){return juce::Time::getMillisecondCounterHiRes();} }
int main(){
 PluginStateModel a; a.selectBar(10);a.selectCount(4);a.selectTab(0);a.setBypass(true);
 a.setCountPreset(10,2,PluginStateModel::ScratchPreset::backspin);a.setCountPreset(10,4,PluginStateModel::ScratchPreset::chirp);a.setCountPreset(10,12,PluginStateModel::ScratchPreset::zigzag);
 a.setCountLength(10,4,PluginStateModel::NoteLength::quarter);a.setCountSpeed(10,4,1.75f);a.setCountPitch(10,4,-12);a.setCountDepth(10,4,.5f);a.setCountMotion(10,4,{{.1f,.2f},{.4f,.5f},{.8f,.9f}});
 auto t=a.toValueTree();PluginStateModel b;check(b.fromValueTree(t),"round-trip");auto s=b.getCount(10,4);check(b.getCount(10,2).preset==PluginStateModel::ScratchPreset::backspin&&b.getCount(10,12).preset==PluginStateModel::ScratchPreset::zigzag,"1024-slot independence");check(s.length==PluginStateModel::NoteLength::quarter&&s.speed==1.75f&&s.pitch==-12&&s.depth==.5f&&b.getCount(10,2).speed==1&&b.getCount(10,12).depth==1,"parameter independence");check(s.preset==PluginStateModel::ScratchPreset::custom&&s.customMotion&&s.motion.size()==3&&s.motion[1].x==.4f&&s.motion[1].y==.5f,"motion custom round-trip");auto u=b.getUiState();check(u.selectedTab==0&&u.selectedBar==10&&u.selectedCount==4&&u.bypass,"UI state restore");
 auto bad=t;auto bars=bad.getChildWithName("Bars");auto bar=bars.getChild(10);auto count=bar.getChild(4);count.setProperty("preset",999,nullptr);count.setProperty("length",999,nullptr);count.setProperty("speed",std::numeric_limits<double>::infinity(),nullptr);count.setProperty("pitch",std::numeric_limits<double>::quiet_NaN(),nullptr);count.setProperty("depth",-3.0,nullptr);juce::ValueTree p("Point");p.setProperty("x",999.0,nullptr);p.setProperty("y",-8.0,nullptr);count.addChild(p,-1,nullptr);juce::ValueTree duplicate("Count");duplicate.setProperty("index",4,nullptr);bar.addChild(duplicate,-1,nullptr);PluginStateModel c;check(c.fromValueTree(bad)&&c.getCount(10,4).speed<=2&&c.getCount(10,4).depth>=0,"invalid state clamped safely");
 PluginStateModel preserved=c;juce::ValueTree future("ToyotomiHideyoshiState");future.setProperty("stateVersion",99,nullptr);check(!c.fromValueTree(future)&&c.getCount(10,4).speed==preserved.getCount(10,4).speed,"future version preserves state");juce::ValueTree missing("ToyotomiHideyoshiState");check(!c.fromValueTree(missing),"missing version rejected");PluginStateModel empty;check(empty.fromValueTree(empty.toValueTree()),"empty state");
 auto measure=[](int slots){PluginStateModel x;std::vector<PluginStateModel::MotionPoint> m;for(int i=0;i<256;++i)m.push_back({i/255.f,1.f-i/255.f});for(int i=0;i<slots;++i)x.setCountMotion(i/16,i%16,m);auto st=now();auto tree=x.toValueTree();auto mid=now();auto b=bytes(x);PluginStateModel y;auto rs=now();y.fromValueTree(tree);auto re=now();std::cout<<"MEASURE slots="<<slots<<" bytes="<<b.getSize()<<" serializeMs="<<(mid-st)<<" restoreMs="<<(re-rs)<<'\n';};measure(0);measure(1);measure(16);return ok?0:1; }
